services:
  app:
    container_name: ${NAME_CONTAINER}
    image: ${DOCKER_IMAGE_NAME}:1.0
    restart: always
    ports:
      - 3000:3000
    networks:
      - red_ayra
      
networks:
  red_ayra:
    external: true