global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus' # To get metrics about the exporter itself
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter' # To get metrics about the exporter itself
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor' # To get metrics about the exporter itself
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'backend' # To get metrics about the exporter itself
    static_configs:
      - targets: ['stakepad-server:3001']

  - job_name: 'frontend' # To get metrics about the exporter itself
    static_configs:
      - targets: ['ui:3000']
