global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'docker' # To get metrics about the exporter itself
    docker_sd_configs:
      - host: 'unix:///var/run/docker.sock'
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: instance
      - source_labels:
          [__meta_docker_container_label_com_docker_swarm_service_name]
        target_label: job

  - job_name: 'prometheus' # To get metrics about the exporter itself
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter' # To get metrics about the exporter itself
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor' # To get metrics about the exporter itself
    static_configs:
      - targets: ['cadvisor:8080']

  # - job_name: 'backend' # To get metrics about the exporter itself
  #   static_configs:
  #     - targets: ['stakepad-server:3001']

  # - job_name: 'frontend' # To get metrics about the exporter itself
  #   static_configs:
  #     - targets: ['ui:3000']
