name: Deploy Alexander

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Files
        uses: actions/checkout@v4

      - name: Save Docker image as tar file
        run: echo "${{ secrets.varEntorno }}" > .env

      - name: Display Dockerfile content
        run: |
          if [ -s Dockerfile ]; then
            echo "Dockerfile created successfully"
          else
            echo "Dockerfile is empty or not created"
            exit 1
          fi
