name: Deploy Alexander

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Files
        uses: actions/checkout@v4

      - name: Save Docker image as tar file
        run: |
          echo "Nombre del repositorio: $(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
          docker build -t $(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]') .
          docker save -o $(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]').tar $(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: ls de los archivos
        run: |
          echo ls
          echo ls -l -a
